services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    labels:
      com.github.nginx-proxy.nginx: ""
    environment:
      DEFAULT_HOST: uptime.engib.ru
    networks:
      - uptime-kuma_default
      - zitadel_default
    restart: unless-stopped

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: narek@engibaryan.ru
    networks:
      - uptime-kuma_default
      - zitadel_default
    restart: unless-stopped

networks:
  uptime-kuma_default:
    external: true
  zitadel_default:
    external: true

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}
