---
- name: Setup OS
  become: true
  hosts: "{{ target_hosts | default('vps') }}"

  roles:
    - GROG.fqdn
    - GROG.package
    - geerlingguy.pip
    - geerlingguy.docker
    - name: GROG.management-user
      ignore_errors: true
    - name: diodonfrost.ohmyzsh
      ignore_errors: true
      vars:
        ohmyzsh_theme: kphoen
        ohmyzsh_users: [narek]
        ohmyzsh_plugins: [git, sudo]
    - willshersystems.sshd
