services:
  zitadel:
    restart: unless-stopped
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkeyFromEnv --tlsMode disabled'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "${POSTGRES_USER_PASSWORD}"
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: smtp.timeweb.ru:2525
      # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: zitadel@engib.ru
      # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: "${SMTP_PASSWORD}"
      ZITADEL_MASTERKEY: "${ZITADEL_MASTERKEY}"
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_EXTERNALDOMAIN: zitadel.engib.ru
      VIRTUAL_HOST: zitadel.engib.ru
      LETSENCRYPT_HOST: zitadel.engib.ru
      VIRTUAL_PORT: 8080
    depends_on:
      db:
        condition: 'service_healthy'

  db:
    restart: unless-stopped
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"
      POSTGRES_DB: zitadel
    volumes:
    - zitadel-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

volumes:
  zitadel-db:
